### ISSUE TITLE
additional category 'SensorAssembly' needed

### ISSUE THREAD

**Issue by gieschef** [gieschef/EQX#6]
In Taskforcemeeting on 2019-11-13 it was decided to introduce a new category 'SensorAssembly' for more than one sensor packed as an assembly unit.
This could be for example multidimensional measurement unit like IR TRACC or similar Equipment.

**Comment by gieschef** [comment]
Intention : usually an assembly has more than one Serial number, but they are functionally related. 
Individual devices that are calibrated together.

Decision of Taskforce : eliminate sensorassembly and use 'Multi-Axis Sensor'instead.

**Comment by NathanBrownDTS** [comment]
For history, Stefan Irwin also proposed an additional enum: FunctionalAssembly to indicate that the individual sensors function together as a whole assembly. This would differentiate a 3d-displacement sensor (IR-TRACC, etc) from for instance a 6-axis load cell.

**Comment by NathanBrownDTS** [comment]
-

**Comment by NathanBrownDTS** [comment]
-

**Comment by NathanBrownDTS** [comment]
-
